dist: xenial

language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt

script:
    - source travis.sh pytest
    - source travis.sh flake8

after_success:
  - source travis.sh success $WEBHOOK_URL

after_failure:
  - source travis.sh failure $WEBHOOK_URL
