# Generated by Django 2.2 on 2019-05-13 12:55

import billapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('logo_path', models.ImageField(upload_to=billapp.models.assos_image_path)),
                ('email', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('premium', models.BooleanField()),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('begin_register', models.DateTimeField()),
                ('end_register', models.DateTimeField()),
                ('place', models.CharField(max_length=128)),
                ('price_ionis', models.FloatField()),
                ('price', models.FloatField()),
                ('ext_capacity', models.IntegerField()),
                ('int_capacity', models.IntegerField()),
                ('staff_capacity', models.IntegerField()),
                ('promotion_image_path', models.ImageField(upload_to=billapp.models.promo_image_path)),
                ('validation_state', models.SmallIntegerField(choices=[(1, 'Need authorization'), (2, 'Approved by the association'), (3, 'Approuved by EPITA'), (4, 'Authorized')], default=1)),
                ('request_for_approuval', models.BooleanField(default=False)),
                ('show_capacity', models.BooleanField()),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billapp.Association')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.BooleanField()),
                ('state', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billapp.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventStaffCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billapp.Association')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billapp.Event')),
            ],
        ),
        migrations.CreateModel(
            name='AssociationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField()),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billapp.Association')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
