# Generated by Django 3.0.dev20190305002527 on 2019-03-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=128)),
                ('pseudo', models.CharField(max_length=64)),
                ('password', models.BinaryField(max_length=20)),
                ('role', models.IntegerField()),
            ],
        ),
    ]
