# Generated by Django 3.0.dev20190305002527 on 2019-03-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo_path', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
    ]
