# Generated by Django 2.2 on 2019-05-14 00:34

import billapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0002_auto_20190513_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='request_for_approuval',
            new_name='request_for_approval',
        ),
        migrations.AlterField(
            model_name='association',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='association',
            name='email',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='event',
            name='ext_capacity',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='int_capacity',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_ionis',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='promotion_image_path',
            field=models.ImageField(blank=True, upload_to=billapp.models.promo_image_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='staff_capacity',
            field=models.SmallIntegerField(),
        ),
    ]
