# Generated by Django 3.0.dev20190305002527 on 2019-03-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0002_association'),
    ]

    operations = [
        migrations.RenameField(
            model_name='association',
            old_name='Logo_path',
            new_name='logo_path',
        ),
        migrations.AddField(
            model_name='association',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
