# Generated by Django 3.0.dev20190305002527 on 2019-03-16 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0003_auto_20190316_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField()),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billapp.Association')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billapp.User')),
            ],
        ),
    ]
