# Generated by Django 2.2 on 2019-05-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0003_auto_20190514_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ext_capacity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='int_capacity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='staff_capacity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
