# Generated by Django 3.0.dev20190305002527 on 2019-03-16 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0004_associationuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='logo_path',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('premium', models.BooleanField()),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('begin_register', models.DateTimeField()),
                ('end_register', models.DateTimeField()),
                ('place', models.CharField(max_length=128)),
                ('price_ionis', models.IntegerField()),
                ('price', models.IntegerField()),
                ('ext_capacity', models.IntegerField()),
                ('int_capacity', models.IntegerField()),
                ('staff_capacity', models.IntegerField()),
                ('promotion_image_path', models.CharField(max_length=128)),
                ('validation_state', models.BooleanField()),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billapp.Association')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='billapp.User')),
            ],
        ),
    ]
