# Generated by Django 2.2 on 2019-06-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0005_association_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='url',
            field=models.TextField(default=None, max_length=64, null=True),
        ),
    ]
