# Generated by Django 2.2 on 2019-06-03 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0006_auto_20190603_1858'),
        ('billapp', '0005_auto_20190603_2207'),
    ]

    operations = [
    ]
