# Generated by Django 2.2 on 2019-06-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0007_merge_20190603_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='url',
            field=models.TextField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
