# Generated by Django 3.0.dev20190305002527 on 2019-04-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0007_auto_20190406_1100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssociationUser',
        ),
    ]
