# Generated by Django 2.2 on 2019-06-04 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0008_auto_20190603_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.Association'),
        ),
    ]
