# Generated by Django 2.2 on 2019-06-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0009_ticket_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ionis',
            field=models.BooleanField(default=False),
        ),
    ]
