# Generated by Django 2.1.7 on 2019-04-08 11:19

import billapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0010_auto_20190406_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_ionis',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='promotion_image_path',
            field=models.ImageField(upload_to=billapp.models.image_path),
        ),
    ]
