# Generated by Django 2.2 on 2019-06-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0010_ticket_ionis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ionis',
            field=models.BooleanField(),
        ),
    ]
