# Generated by Django 2.2 on 2019-04-13 09:24

import billapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0011_auto_20190408_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='logo_path',
            field=models.ImageField(upload_to=billapp.models.assos_image_path),
        ),
    ]
