# Generated by Django 2.2 on 2019-05-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0012_auto_20190413_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_capacity',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
