# Generated by Django 2.2 on 2019-05-08 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0013_event_show_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStaffCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billapp.Association')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billapp.Event')),
            ],
        ),
    ]
