# Generated by Django 2.2 on 2019-05-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0014_eventstaffcapacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='request_for_approuval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='validation_state',
            field=models.SmallIntegerField(choices=[(1, 'Need authorization'), (2, 'Approved by the association'), (3, 'Approuved by EPITA'), (4, 'Authorized')]),
        ),
    ]
